import { cva } from "class-variance-authority";

export const GridItemVariants = cva(`relative`, {
  variants: {
    alignSelf: {
      start: "self-start",
      center: "self-center",
      end: "self-end",
      stretch: "self-stretch",
      baseline: "self-baseline",
    },
    justifySelf: {
      start: "justify-self-start",
      center: "justify-self-center",
      end: "justify-self-end",
      stretch: "justify-self-stretch",
      baseline: "justify-self-baseline",
    },
    placeSelf: {
      start: "place-self-start",
      center: "place-self-center",
      end: "place-self-end",
      stretch: "place-self-stretch",
      baseline: "place-self-baseline",
    },
  },
});

export const GridVariants = cva(`grid`, {
  variants: {
    align: {
      start: "items-start",
      center: "items-center",
      end: "items-end",
      stretch: "items-stretch",
      baseline: "items-baseline",
    },
    justify: {
      start: "justify-start",
      center: "justify-center",
      end: "justify-end",
      between: "justify-between",
    },
    flow: {
      row: "grid-flow-row",
      column: "grid-flow-column",
      dense: "grid-flow-dense",
      rowDense: "grid-flow-row-dense",
      columnDense: "grid-flow-column-dense",
    },
    gap: {
      1: `gap-space-1`,
      2: `gap-space-2`,
      3: `gap-space-3`,
      4: `gap-space-4`,
      5: `gap-space-5`,
      6: `gap-space-6`,
      7: `gap-space-7`,
      8: `gap-space-8`,
      9: `gap-space-9`,
      10: `gap-space-10`,
      11: `gap-space-11`,
      12: `gap-space-12`,
      13: `gap-space-13`,
      14: `gap-space-14`,
      15: `gap-space-15`,
    },
    gapX: {
      1: `gap-x-space-1`,
      2: `gap-x-space-2`,
      3: `gap-x-space-3`,
      4: `gap-x-space-4`,
      5: `gap-x-space-5`,
      6: `gap-x-space-6`,
      7: `gap-x-space-7`,
      8: `gap-x-space-8`,
      9: `gap-x-space-9`,
      10: `gap-x-space-10`,
      11: `gap-x-space-11`,
      12: `gap-x-space-12`,
      13: `gap-x-space-13`,
      14: `gap-x-space-14`,
      15: `gap-x-space-15`,
    },
    gapY: {
      1: `gap-y-space-1`,
      2: `gap-y-space-2`,
      3: `gap-y-space-3`,
      4: `gap-y-space-4`,
      5: `gap-y-space-5`,
      6: `gap-y-space-6`,
      7: `gap-y-space-7`,
      8: `gap-y-space-8`,
      9: `gap-y-space-9`,
      10: `gap-y-space-10`,
      11: `gap-y-space-11`,
      12: `gap-y-space-12`,
      13: `gap-y-space-13`,
      14: `gap-y-space-14`,
      15: `gap-y-space-15`,
    },
  },
  defaultVariants: {
    align: "stretch",
    justify: "start",
  },
});
