import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Menu from "@/core/components/Menu/Menu";
import { ThemeProvider } from "@/providers/theme-provider";
import Header from "@/core/components/Header/Header";
import ToastProvider from "@/providers/toast-provider";
import SessionProvider from "@/providers/session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            storageKey="ks-theme"
            enableSystem={false}
          >
            <ToastProvider />
            <Menu />
            <Header offsetHeight={256} />
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
